SELECT
    OUTLET_CODE,
    OUTLET_NAME,
    AIRPORT_CODE,
    NUMBER_OF_SEATS,
    TERMINAL,
--    CONCOURSE,
    OUTLET_STATUS,
    OUTLET_TYPE,
    ISO_COUNTRY_CODE,
--    AIRSIDE_LANDSIDE,
    OPERATOR,
    OPERATOR_CODE,
    -- Opening hours by day of week
    OPENING_HOURS
FROM SUBDM_COLLINSON_INVENTORY_DH.DATAMART.DIM__OUTLET_DH
QUALIFY ROW_NUMBER() OVER (PARTITION BY OUTLET_CODE ORDER BY UPDATED_AT DESC) = 1
ORDER BY OUTLET_CODE
