SELECT
    CODE AS OUTLET_CODE,
    NAME AS OUTLET_NAME,
    LOCATION_CODE_TEXT AS AIRPORT_CODE,
    NUMBER_OF_SEATS,
    TERMINAL,
    CONCOURSE,
    ACCOUNT_STATUS,
    INVENTORY_CATEGORY AS OUTLET_TYPE,
    ISO_COUNTRY_CODE,
    AIRSIDE_LANDSIDE,
    OPERATOR_CODE,
    -- Opening hours by day of week
    MONDAY_OPEN_TIME,
    MONDAY_CLOSE_TIME,
    TUESDAY_OPEN_TIME,
    TUESDAY_CLOSE_TIME,
    WEDNESDAY_OPEN_TIME,
    WEDNESDAY_CLOSE_TIME,
    THURSDAY_OPEN_TIME,
    THURSDAY_CLOSE_TIME,
    FRIDAY_OPEN_TIME,
    FRIDAY_CLOSE_TIME,
    SATURDAY_OPEN_TIME,
    SATURDAY_CLOSE_TIME,
    SUNDAY_OPEN_TIME,
    SUNDAY_CLOSE_TIME,
    LAST_MODIFIED_DATE
FROM STAGING_QUALITY.SF_PARTNERSHIP.SQ_SF_PARTNERSHIP__ACCOUNT
QUALIFY ROW_NUMBER() OVER (PARTITION BY CODE ORDER BY LAST_MODIFIED_DATE DESC) = 1
ORDER BY CODE
