start_date: '2026-01-01'
end_date: '2026-01-08'  # inclusive

flight_service: 'J'

paths:
 sql_template:
  get_15min_flights: 'SQL_templates/flights/extract_15min_interval_non-null_historical_flights.sql'
 export_directory: 'historical_flights'    # for local run only

filename_base: 'oag_actual_15min'
